# Players will teleported to this world when a reset happens
# or when they type the SPAWN subcommand
spawn-world: "world"

# Enable resource world autoreset
auto-reset: true

# If enabled you can use your custom worlds uploading them in the plugin
# data folder and renaming them with the name specified in dimension config
# For example: world_resource, world_resource_nether, world_resource_end
use-custom-worlds: false

# Reset interval in days
reset-interval: 30

# Reset the resource world if players are online in the server
# true: Players in the resource world will be teleported to the spawn
# false: Wait when the server is empty
reset-with-players-online: false

# Random teleport range for resource world (set 0 disable)
teleport-range: 200

# Teleport delay in seconds
teleport-delay: 5

# Teleport delay in seconds when the player clicks on a tp sign
# instead of typing the TP command
signs-teleport-delay: 0

# Teleport to resource world cooldown in seconds
teleport-cooldown: 60

# With permission pearresourceworld.tp.delay.bypass will bypass the delay
bypass-delay-permission: true

# With permission pearresourceworld.tp.cooldown.bypass will bypass the cooldown
bypass-cooldown-permission: true

# RESOURCE WORLD SETTINGS
# Valid difficulties: PEACEFUL, EASY, NORMAL, HARD
# Valid world types: DEFAULT, FLAT, LARGEBIOMES, AMPLIFIED, BUFFET
resource-world-settings:
  teleport-spawn-on-quit: true
  disable-set-respawn: true
  keep-inventory: false
  difficulty: NORMAL
  custom-seed: ""
  pvp: true
  always-day: false
  allow-nether-portals: true
  allow-end-portals: true
  disable-dragon-battle: true
  prevent-dragon-respawn: true
  world-type: DEFAULT
  generate-structures: true
  keep-spawn-in-memory: false

# If resource nether/end is disabled and portals are enabled
# they will bring to the nether/end dimension in the default world
resource-dimensions:
  overworld:
    name: "world_resource"
    border: 5000
  nether:
    name: "world_resource_nether"
    enabled: true
    border: 625
  end:
    name: "world_resource_end"
    enabled: false
    border: 2500

# Block blacklisted commands in resource world
enable-command-blacklist: true

# Insert commands without '/'
# This will block also the ':' syntax (for example '/pluginName:sethome')
command-blacklist:
  - sethome